"""Per-section writer agents for the Layer-4 manuscript (ADR-007).

Each function emits a LaTeX fragment built ONLY from the Layer-1->3 artifacts
(``asald_results.json``, ``surface_fidelity.json``, ``citation_repository.json``) -- no
invented numbers, real DOIs only. Deterministic by default (fully reproducible); an
optional LLM pass can polish prose without introducing new quantities.
"""

from __future__ import annotations

import re


def latex_escape(text: str) -> str:
    if text is None:
        return ""
    repl = {
        "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
        "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = []
    for ch in str(text):
        out.append(repl.get(ch, ch))
    return "".join(out)


def title(rich: dict) -> str:
    hyp = rich.get("hypothesis", {})
    return (
        f"In-Silico Validation of Area-Selective ALD: {latex_escape(hyp.get('inhibitor',''))} "
        f"Passivation of {latex_escape(hyp.get('non_growth_surface',''))} for "
        f"{latex_escape(hyp.get('precursor',''))}-Based {latex_escape(hyp.get('target_film',''))} Growth"
    )


def abstract(rich: dict) -> str:
    hyp = rich.get("hypothesis", {})
    ads = rich.get("inhibitor_adsorption", {})
    sel = rich.get("selectivity", {})
    verdict = rich.get("verdict", "inconclusive").replace("_", " ")
    return (
        f"We computationally test whether {latex_escape(hyp.get('inhibitor',''))} selectively "
        f"passivates the {latex_escape(hyp.get('non_growth_surface',''))} non-growth surface "
        f"(NGS) while enabling {latex_escape(hyp.get('precursor',''))}-based "
        f"{latex_escape(hyp.get('target_film',''))} growth on the "
        f"{latex_escape(hyp.get('growth_surface',''))} growth surface (GS). Over a gated "
        f"ensemble of experiment-faithful amorphous surfaces we compute a differential "
        f"blocking coverage of {ads.get('differential_blocking','n/a')} and a selectivity "
        f"$S = {sel.get('S_at_target_mean','n/a')} \\pm {sel.get('S_at_target_std','n/a')}$ at "
        f"{sel.get('target_thickness_nm','n/a')} nm against a target of "
        f"{sel.get('target',0):.0%}. The hypothesis is {latex_escape(verdict)}."
    )


def introduction(rich: dict) -> str:
    hyp = rich.get("hypothesis", {})
    return (
        "Area-selective atomic layer deposition (AS-ALD) works by dosing a molecular "
        "inhibitor that selectively chemisorbs on the non-growth surface (NGS) and blocks "
        "the ALD precursor there, while leaving the growth surface (GS) reactive. The film "
        "nucleates on the GS and is delayed on the NGS; that nucleation delay is the "
        "selectivity. Computed selectivity is dominated by the assumed amorphous surface "
        "model, so surface fidelity is the central rigor question. Here we validate the "
        f"intervention: \\emph{{{latex_escape(hyp.get('statement',''))}}}"
    )


def methods(rich: dict, fidelity: dict) -> str:
    prov = rich.get("provenance", {})
    engine = prov.get("engine", "n/a")
    tier = prov.get("compute_tier", 0)
    surf_tbl = _surface_table(fidelity)
    engine_line = (
        f"Reactivity was evaluated with the {latex_escape(str(engine))} engine "
        f"(compute tier {tier}"
        + (f", MLIP {latex_escape(str(prov.get('mlip_model')))} on {latex_escape(str(prov.get('mlip_device')))}"
           if tier >= 1 else "")
        + f", T = {prov.get('temperature_K','n/a')} K, ensemble N = {prov.get('ensemble_n','n/a')}). "
        "Foundation-MLIP barriers are known to be underestimated and are reported only as "
        "lower bounds; adsorption energies are anchored to literature values."
    )
    return (
        "\\subsection{Surfaces (Deliverable \\#1)}\n"
        "An ensemble of amorphous slabs was generated by a melt-quench-cleave-saturate-"
        "condense pipeline with an explicit target site density, and every slab was passed "
        "through a fidelity gate rejecting densities outside the experimental band.\n\n"
        + surf_tbl
        + "\n\n\\subsection{Reactivity engine}\n"
        + engine_line
    )


def results(rich: dict) -> str:
    ads = rich.get("inhibitor_adsorption", {})
    sel = rich.get("selectivity", {})
    calib = rich.get("calibration_vs_literature")
    verdict = rich.get("verdict", "inconclusive").replace("_", " ")

    ads_tbl = (
        "\\begin{table}[h]\\centering\n\\caption{Inhibitor adsorption and blocking coverage.}\n"
        "\\begin{tabular}{lcc}\\toprule\n"
        " & Non-growth surface & Growth surface \\\\\\midrule\n"
        f"$\\Delta E_{{ads}}$ (eV) & ${ads.get('dE_ngs_mean_eV','n/a')} \\pm {ads.get('dE_ngs_std_eV','n/a')}$ "
        f"& ${ads.get('dE_gs_mean_eV','n/a')} \\pm {ads.get('dE_gs_std_eV','n/a')}$ \\\\\n"
        f"Blocking coverage & {ads.get('blocking_ngs_mean','n/a')} & {ads.get('blocking_gs_mean','n/a')} \\\\\n"
        "\\bottomrule\\end{tabular}\\end{table}\n"
    )
    calib_tbl = ""
    if calib:
        calib_tbl = (
            "\\begin{table}[h]\\centering\n\\caption{MLIP-vs-literature calibration.}\n"
            "\\begin{tabular}{lc}\\toprule\n"
            f"Predicted $\\Delta E_{{NGS}}$ (eV) & {calib.get('predicted_dE_ngs_eV','n/a')} \\\\\n"
            f"Literature $\\Delta E_{{NGS}}$ (eV) & {calib.get('literature_dE_ngs_eV','n/a')} \\\\\n"
            f"Absolute error (eV) & {calib.get('abs_error_eV','n/a')} \\\\\n"
            f"Validity flag & {latex_escape(str(calib.get('validity_flag','n/a')))} \\\\\n"
            "\\bottomrule\\end{tabular}\\end{table}\n"
        )
    verdict_line = (
        f"The differential blocking coverage is {ads.get('differential_blocking','n/a')}. "
        f"The resulting selectivity is $S = {sel.get('S_at_target_mean','n/a')} \\pm "
        f"{sel.get('S_at_target_std','n/a')}$ at {sel.get('target_thickness_nm','n/a')} nm "
        f"(target {sel.get('target',0):.0%}), so the hypothesis is "
        f"\\textbf{{{latex_escape(verdict)}}}."
    )
    return ads_tbl + calib_tbl + verdict_line


def discussion(rich: dict) -> str:
    ads = rich.get("inhibitor_adsorption", {})
    return (
        "The selectivity is driven by the differential blocking coverage "
        f"({ads.get('differential_blocking','n/a')}) rather than by raw Langmuir coverage, "
        "which saturates at ALD temperature. Because only chemisorbed, purge-surviving "
        "inhibitor blocks the precursor, the chemisorb-on-NGS / physisorb-on-GS contrast is "
        "what confers area selectivity. Selectivity degrades past the nucleation-delay "
        "breakthrough, which is the expected qualitative shape for area-selective growth."
    )


def conclusion(rich: dict) -> str:
    hyp = rich.get("hypothesis", {})
    verdict = rich.get("verdict", "inconclusive").replace("_", " ")
    return (
        f"The intervention pairing {latex_escape(hyp.get('inhibitor',''))} with "
        f"{latex_escape(hyp.get('precursor',''))} was {latex_escape(verdict)} in silico over a "
        "gated surface ensemble with a literature-calibrated reactivity engine. Every number "
        "in this manuscript traces to the recorded validation artifacts."
    )


def bibliography(citations: list[dict]) -> str:
    lines = []
    for c in citations:
        cid = c.get("id", "ref")
        short = c.get("title", "") or cid
        authors = ", ".join(c.get("authors", [])[:3])
        year = c.get("year")
        venue = c.get("venue") or ""
        doi = c.get("doi")
        entry = " ".join(
            p for p in [
                latex_escape(authors),
                f"({year})." if year else "",
                latex_escape(short) + ".",
                latex_escape(venue) + "." if venue else "",
                (f"\\url{{https://doi.org/{doi}}}" if doi else ""),
            ] if p
        )
        lines.append(f"\\bibitem{{{_safe_key(cid)}}} {entry}")
    return "\n".join(lines) if lines else "\\bibitem{none} No citations recorded."


def _safe_key(cid: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", cid) or "ref"


def _surface_table(fidelity: dict) -> str:
    rows = []
    for group_key, label in (("growth_surface", "GS"), ("non_growth_surface", "NGS")):
        group = fidelity.get(group_key, {})
        for i, rep in enumerate(group.get("reports", [])):
            band = rep.get("acceptance_band", ["", ""])
            rows.append(
                f"{label}-{i} & {latex_escape(rep.get('material',''))} & "
                f"{rep.get('site_density_per_nm2','n/a')} & "
                f"[{band[0]}, {band[1]}] & "
                f"{'pass' if rep.get('passed') else 'fail'} \\\\"
            )
    if not rows:
        return ""
    return (
        "\\begin{table}[h]\\centering\n\\caption{Per-surface site density vs the "
        "experimental band and gate outcome.}\n"
        "\\begin{tabular}{lcccc}\\toprule\n"
        "Surface & Material & Density (nm$^{-2}$) & Band & Gate \\\\\\midrule\n"
        + "\n".join(rows)
        + "\n\\bottomrule\\end{tabular}\\end{table}"
    )
